---

- hosts: proxmoxHosts
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3" 
  tasks:

    - name: update repos
      apt: 
        update_cache: yes

    - name: Install Packages
      apt:
        name:
          - vim
          - ifupdown2
          - ethtool
          - git
          - corosync-qdevice

    # - name: Copy checksend backup
    #   copy: src=check_send_backup.py dest=~

    # - name: Set up cron job
    #   ansible.builtin.cron:
    #     name: "Check and send backup"
    #     minute: "30"
    #     hour: "4"
    #     job: "python3 ~/check_send_backup.py"