---

- hosts: proxmoxHosts
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3" 
  tasks:

    - name: update repos
      apt: 
        update_cache: yes

    - name: Install Packages
      apt:
        name:
          - vim
          - ifupdown2
          - ethtool
          - git
          - corosync-qdevice

    - name: Pull required server software from git
      ansible.builtin.git:
        repo: "https://github.com/derekf55/server_scripts.git"
        dest: ~/server_scripts/

    - name: Set up cron job
      ansible.builtin.cron:
        name: "Check and send backup"
        minute: "30"
        hour: "4"
        job: "python3 ~/server_scripts/check_send_backup.py"