---

- hosts: testHost
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/python3" 
  tasks:

    - name: update repos
      apt: 
        update_cache: yes

    - name: Install Packages
      apt:
        name:
          - vim
          - ifupdown2
          - ethtools
          - git

    - name: Install derek_fucntions
      import_playbook: install_derek_functions.yaml 
    
    - name: Copy checksend backup
      copy: src=check_send_backup.py dest=~

    - name: Set up cron job
      ansible.builtin.cron:
        name: "Check and send backup"
        minute: "0"
        hour: "5"
        job: "python3 ~/check_send_backup.py"